<?php

/**
 *
 * Configuration file, generated by the iTop configuration wizard
 *
 * The file is used in MetaModel::LoadConfig() which does all the necessary initialization job
 *
 */
$MySettings = array(

	// access_message: Message displayed to the users when there is any access restriction
	//      default: 'iTop is temporarily frozen, please wait... (the admin team)'
	'access_message' => 'Nous vous informons que l application est actuellement en MAINTENANCE. Pendant cette période, vous ne pourrez pas effectuer de modifications, mais sachant que vous pourrez naviguer sur l application. La durée estimée de la maintenance jusqu a 20:00. Si vous effectuez des traitements urgents sur l application, veuillez contacter le département IT de CFAC Group',

	// access_mode: Access mode: ACCESS_READONLY = 0, ACCESS_ADMIN_WRITE = 2, ACCESS_FULL = 3
	//	default: 3
	'access_mode' => 3,

	// activity_panel.entry_form_opened_by_default: Whether or not the new entry form will be automatically opened when viewing an object.
	//	default: false
	'activity_panel.entry_form_opened_by_default' => false,

	// activity_panel.show_author_name_below_entries: Whether or not to show the author friendlyname next to the date on the last entry.
	//	default: false
	'activity_panel.show_author_name_below_entries' => false,

	'allowed_login_types' => 'form|external|basic',

	// apc_cache.enabled: If set, the APC cache is allowed (the PHP extension must also be active)
	//	default: true
	'apc_cache.enabled' => true,

	// apc_cache.query_ttl: Time to live set in APC for the prepared queries (seconds - 0 means no timeout)
	//	default: 3600
	'apc_cache.query_ttl' => 3600,

	// app_root_url: Root URL used for navigating within the application, or from an email to the application (you can put $SERVER_NAME$ as a placeholder for the server's name)
	//	default: ''
	//'app_root_url' => 'http://10.0.1.198/itop/',
	'app_root_url' => 'http://localhost:8056/itop_from_server_local_cfac/',

	// behind_reverse_proxy: If true, then proxies custom header (X-Forwarded-*) are taken into account. Use only if the webserver is not publicly accessible (reachable only by the reverse proxy)
	//	default: false
	'behind_reverse_proxy' => false,

	// cron_max_execution_time: Duration (seconds) of the cron.php script : if exceeded the script will exit even if there are remaining tasks to process. Must be shorter than php max_execution_time setting (note than when using CLI, this is set to 0 by default which means unlimited). If cron.php is ran via web, it must be shorter than the web server response timeout.
	//	default: 600
	'cron_max_execution_time' => 600,

	// csv_file_default_charset: Character set used by default for downloading and uploading data as a CSV file. Warning: it is case sensitive (uppercase is preferable).
	//	default: 'ISO-8859-1'
	'csv_file_default_charset' => 'ISO-8859-1',

	'csv_import_charsets' => array (
	),

	// csv_import_history_display: Display the history tab in the import wizard
	//	default: false
	'csv_import_history_display' => false,

	// date_and_time_format: Format for date and time display (per language)
	//	default: array (
	//		  'default' => 
	//		  array (
	//		    'date' => 'Y-m-d',
	//		    'time' => 'H:i:s',
	//		    'date_time' => '$date $time',
	//		  ),
	//		)
	'date_and_time_format' => array('default' => array('date' => 'Y-m-d', 'time' => 'H:i:s', 'date_time' => '$date $time')),

	// Original SetUp
/*
	'db_host' => 'localhost',

	'db_name' => 'itopcfac_v20230316',

	'db_pwd' => 'iheb112233*',

	'db_subname' => '',

	'db_user' => 'root',
*/
	'db_host' => 'localhost',

	'db_name' => 'itopcfac_29_02_2024',

	'db_pwd' => '',

	'db_subname' => '',

	'db_user' => 'root',

	// deadline_format: The format used for displaying "deadline" attributes: any string with the following placeholders: $date$, $difference$
	//	default: '$difference$'
	'deadline_format' => '$difference$',

	'default_language' => 'FR FR',

	// email_asynchronous: If set, the emails are sent off line, which requires cron.php to be activated. Exception: some features like the email test utility will force the serialized mode
	//	default: false
	'email_asynchronous' => false,

	// email_default_sender_address: Default address provided in the email from header field.
	//	default: ''
	'email_default_sender_address' => '',

	// email_default_sender_label: Default label provided in the email from header field.
	//	default: ''
	'email_default_sender_label' => '',

	//customization de CFAC Group to make the emails Work

	// email_transport: Mean to send emails: PHPMail (uses the function mail()), SMTP (implements the client protocol) or SMTP_OAuth (connect to the server using OAuth 2.0)
	//	default: 'PHPMail'
	// 'email_transport' => 'PHPMail',
	'email_transport' => 'SMTP',
	
	// email_transport_smtp.encryption:tls ou ssl (optional)
	//	default: ''
	'email_transport_smtp.encryption' => 'tls',
	
	// email_transport_smtp.host: host name or IP address (optional)
	//  default: 'localhost' 
	'email_transport_smtp.host' => 'smtp.gmail.com',

	// email_transport_smtp.password: Authentication password (optional)
	'email_transport_smtp.password' => 'qmth jbgf vvdp aorh',

	// email_transport_smtp.password: port number (optional)
	// 		default: 25
	'email_transport_smtp.port' => 587,

	// email_transport_smtp.username: Authentication user (optional)
	// 		default: 25
	'email_transport_smtp.username' => 'serviceclient@cfac.com.tn',

	// end of the customization

	// email_validation_pattern: Regular expression to validate/detect the format of an eMail address
	//	default: '[a-zA-Z0-9._&\'-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z0-9-]{2,}'
	'email_validation_pattern' => '[a-zA-Z0-9._&\'-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z0-9-]{2,}',

	'encryption_key' => '72a3da777384f86e7709ff186123942b10e0ebc5014a879ca3ccc887e6019bc7',

	'encryption_library' => 'Sodium',

	'ext_auth_variable' => '$_SERVER[\'REMOTE_USER\']',

	'fast_reload_interval' => '60',

	// graphviz_path: Path to the Graphviz "dot" executable for graphing objects lifecycle
	//	default: '/usr/bin/dot'
	'graphviz_path' => '/usr/bin/dot',

	// high_cardinality_classes: List of classes with high cardinality (Force manual submit of search)
	//	default: array (
	//		)
	'high_cardinality_classes' => array(),

	// inline_image_max_display_width: The maximum width (in pixels) when displaying images inside an HTML formatted attribute. Images will be displayed using this this maximum width.
	//	default: '250'
	'inline_image_max_display_width' => '250',

	// inline_image_max_storage_width: The maximum width (in pixels) when uploading images to be used inside an HTML formatted attribute. Images larger than the given size will be downsampled before storing them in the database.
	//	default: '1600'
	'inline_image_max_storage_width' => '1600',

	// link_set_attribute_qualifier: Link set from string: attribute qualifier (encloses both the attcode and the value)
	//	default: '\''
	'link_set_attribute_qualifier' => '\'',

	// link_set_attribute_separator: Link set from string: attribute separator
	//	default: ';'
	'link_set_attribute_separator' => ';',

	// link_set_item_separator: Link set from string: line separator
	//	default: '|'
	'link_set_item_separator' => '|',

	// link_set_value_separator: Link set from string: value separator (between the attcode and the value itself
	//	default: ':'
	'link_set_value_separator' => ':',

	'log_global' => true,

	'log_issue' => true,

	'log_notification' => true,

	'log_web_service' => true,

	'max_display_limit' => '30',

	// max_linkset_output: Maximum number of items shown when getting a list of related items in an email, using the form $this->some_list$. 0 means no limit.
	//	default: 100
	'max_linkset_output' => 100,

	// mentions.allowed_classes: Classes which can be mentioned through the autocomplete in the caselogs. Key of the array must be a single character that will trigger the autocomplete, value must be a DM class (eg. "@" => "Person", "?" => "FAQ")
	//	default: array (
	//		  '@' => 'Person',
	//		)
	'mentions.allowed_classes' => array('@' => 'Person'),

	'min_display_limit' => '20',

	// online_help: Hyperlink to the online-help web page
	//	default: 'http://www.cfacgroup.com/fr/contact'
	'online_help' => 'http://www.cfacgroup.com/fr/contact',

	// optimize_requests_for_join_count: Optimize request joins to minimize the count (default is true, try to set it to false in case of performance issues)
	//	default: true
	'optimize_requests_for_join_count' => true,

	'password_hash_algo' => '2y',

	// php_path: Path to the php executable in CLI mode
	//	default: 'php'
	'php_path' => 'php',

	// search_manual_submit: Force manual submit of search all requests
	//	default: false
	'search_manual_submit' => false,

	'secure_connection_required' => false,

	// session_name: The name of the cookie used to store the PHP session id
	//	default: 'iTop'
	'session_name' => 'iTop',

	// shortcut_actions: Actions that are available as direct buttons next to the "Actions" menu
	//	default: 'UI:Menu:Modify,UI:Menu:New'
	'shortcut_actions' => 'UI:Menu:Modify,UI:Menu:New',

	// source_dir: Source directory for the datamodel files. (which gets compiled to env-production).
	//	default: ''
	'source_dir' => 'datamodels/2.x/',

	'standard_reload_interval' => '300',

	// synchro_trace: Synchronization details: none, display, save (includes 'display')
	//	default: 'none'
	'synchro_trace' => 'none',

	// tag_set_item_separator: Tag set from string: tag label separator
	//	default: '|'
	'tag_set_item_separator' => '|',

	// timezone: Timezone (reference: http://php.net/manual/en/timezones.php). If empty, it will be left unchanged and MUST be explicitly configured in PHP
	//	default: 'Europe/Paris'
	'timezone' => 'Europe/Paris',

	// tracking_level_linked_set_default: Default tracking level if not explicitly set at the attribute level, for AttributeLinkedSet (defaults to NONE in case of a fresh install, LIST otherwise - this to preserve backward compatibility while upgrading from a version older than 2.0.3 - see TRAC #936)
	//	default: 1
	'tracking_level_linked_set_default' => 0,

	// url_validation_pattern: Regular expression to validate/detect the format of an URL (URL attributes and Wiki formatting for Text attributes)
	//	default: '(https?|ftp)\\://([a-zA-Z0-9+!*(),;?&=\\$_.-]+(\\:[a-zA-Z0-9+!*(),;?&=\\$_.-]+)?@)?([a-zA-Z0-9-.]{3,})(\\:[0-9]{2,5})?(/([a-zA-Z0-9:%+\\$_-]\\.?)+)*/?(\\?[a-zA-Z+&\\$_.-][a-zA-Z0-9;:[\\]@&%=+/\\$_.-]*)?(#[a-zA-Z0-9_.-][a-zA-Z0-9+\\$_.-]*)?'
	'url_validation_pattern' => '(https?|ftp)\\://([a-zA-Z0-9+!*(),;?&=\\$_.-]+(\\:[a-zA-Z0-9+!*(),;?&=\\$_.-]+)?@)?([a-zA-Z0-9-.]{3,})(\\:[0-9]{2,5})?(/([a-zA-Z0-9:%+\\$_-]\\.?)+)*/?(\\?[a-zA-Z+&\\$_.-][a-zA-Z0-9;:[\\]@&%=+/\\$_.-]*)?(#[a-zA-Z0-9_.-][a-zA-Z0-9+\\$_.-]*)?',
);

/**
 *
 * Modules specific settings
 *
 */
$MyModuleSettings = array(
	'authent-cas' => array (
		'cas_debug' => false,
		'cas_host' => '',
		'cas_port' => '',
		'cas_context' => '',
		'cas_version' => '',
	),
	'authent-ldap' => array (
		'host' => 'localhost',
		'port' => 389,
		'default_user' => '',
		'default_pwd' => '',
		'base_dn' => 'dc=yourcompany,dc=com',
		'user_query' => '(&(uid=%1$s)(inetuserstatus=ACTIVE))',
		'options' => array (
		  17 => 3,
		  8 => 0,
		),
		'start_tls' => false,
		'debug' => false,
		'servers' => array (
		),
	),
	'itop-attachments' => array (
		'allowed_classes' => array (
		  0 => 'Ticket',
		),
		'position' => 'relations',
		'preview_max_width' => 290,
		'icon_preview_max_size' => 500000,
	),
	'itop-backup' => array (
		'mysql_bindir' => '',
		'week_days' => 'monday, tuesday, wednesday, thursday, friday',
		'time' => '23:30',
		'retention_count' => 5,
		'enabled' => true,
		'itop_backup_incident' => '',
	),
	'approval-base' => array (
		'email_sender' => '',
		'email_reply_to' => '',
		'comment_attcode' => '',
		'list_last_first' => false,
		'enable_reminder' => true,
	),
	'combodo-sla-computation' => array (
		'coverage_oql' => 'SELECT CoverageWindow',
		'holidays_oql' => 'SELECT Holiday',
	),
	'combodo-approval-extended' => array (
		'target_state' => 'new',
		'bypass_profiles' => 'Administrator, Service Manager',
		'reuse_previous_answers' => true,
	),
	'itop-object-copier' => array (
		'rules' => array (
		  'clone_location' => 
		  array (
		    'source_scope' => 'SELECT Location',
		    'allowed_profiles' => 'Administrator,Configuration Manager',
		    'menu_label' => 'Clone...',
		    'menu_label/FR FR' => 'Cloner...',
		    'menu_tooltip' => 'Clone this location...',
		    'menu_tooltip/FR FR' => 'Cloner ce lieu...',
		    'icon' => 'fas fa-clone',
		    'form_label' => 'Cloning %1$s',
		    'form_label/FR FR' => 'Clonage de %1$s',
		    'report_label' => 'Cloned from %1$s',
		    'report_label/FR FR' => 'Cloné depuis %1$s',
		    'dest_class' => 'Location',
		    'preset' => 
		    array (
		      0 => 'clone_scalars(*)',
		      1 => 'reset(name)',
		    ),
		    'retrofit' => 
		    array (
		    ),
		  ),
		  'child_userrequest' => 
		  array (
		    'source_scope' => 'SELECT UserRequest WHERE status NOT IN (\'resolved\',\'closed\')',
		    'allowed_profiles' => 'Support Agent,Administrator',
		    'menu_label' => 'Create a child request...',
		    'menu_label/FR FR' => 'Créer une demande fille...',
		    'menu_tooltip' => 'Create a child request of this request...',
		    'menu_tooltip/FR FR' => 'Créer une demande fille de cette demande...',
		    'icon' => 'fas fa-comment-alt',
		    'form_label' => 'Create a child request from %1$s',
		    'form_label/FR FR' => 'Créer une demande fille depuis %1$s',
		    'report_label' => 'Created from %1$s',
		    'report_label/FR FR' => 'Créée depuis %1$s',
		    'dest_class' => 'UserRequest',
		    'preset' => 
		    array (
		      0 => 'clone(caller_id,org_id,contacts_list,functionalcis_list)',
		      1 => 'copy(id,parent_request_id)',
		    ),
		    'retrofit' => 
		    array (
		    ),
		  ),
		  'userrequest_from_person' => 
		  array (
		    'source_scope' => 'SELECT Person',
		    'allowed_profiles' => 'Support Agent,Administrator',
		    'menu_label' => 'Create a user request...',
		    'menu_label/FR FR' => 'Créer une demande utilisateur...',
		    'menu_tooltip' => 'Create a user request for this person...',
		    'menu_tooltip/FR FR' => 'Créer une demande utilisateur pour cette personne...',
		    'icon' => 'fas fa-comment-alt',
		    'form_label' => 'Create a user request from %1$s',
		    'form_label/FR FR' => 'Créer une demande utilisateur pour %1$s',
		    'report_label' => 'Created from %1$s',
		    'report_label/FR FR' => 'Créée depuis %1$s',
		    'dest_class' => 'UserRequest',
		    'preset' => 
		    array (
		      0 => 'copy(org_id,org_id)',
		      1 => 'copy(id,caller_id)',
		    ),
		    'retrofit' => 
		    array (
		    ),
		  ),
		  'userrequest_from_ci' => 
		  array (
		    'source_scope' => 'SELECT FunctionalCI',
		    'allowed_profiles' => 'Support Agent,Administrator',
		    'menu_label' => 'Create a user request...',
		    'menu_label/FR FR' => 'Créer une demande utilisateur...',
		    'menu_tooltip' => 'Create a user request for this CI...',
		    'menu_tooltip/FR FR' => 'Créer une demande utilisateur pour cet objet...',
		    'icon' => 'fas fa-comment-alt',
		    'form_label' => 'Create a user request from  %1$s',
		    'form_label/FR FR' => 'Créer une demande utilisateur pour %1$s',
		    'report_label' => 'Created from %1$s',
		    'report_label/FR FR' => 'Créée depuis %1$s',
		    'dest_class' => 'UserRequest',
		    'preset' => 
		    array (
		      0 => 'copy(org_id,org_id)',
		      1 => 'add_to_list(id,functionalcis_list,impact,Impacted CI)',
		    ),
		    'retrofit' => 
		    array (
		    ),
		  ),
		  'clone_ci' => 
		  array (
		    'menu_tooltip' => 'Clone this CI...',
		    'menu_tooltip/FR FR' => 'Cloner cet élément...',
		    'icon' => 'fas fa-clone',
		    'source_scope' => 'SELECT FunctionalCI',
		    'allowed_profiles' => 'Administrator,Configuration Manager',
		    'dest_class' => '',
		    'preset' => 
		    array (
		      0 => 'clone_scalars(*)',
		      1 => 'reset(name)',
		    ),
		    'retrofit' => 
		    array (
		    ),
		  ),
		  'userrequest_from_log' => 
		  array (
		    'source_scope' => 'SELECT UserRequest WHERE status IN (\'closed\')',
		    'allowed_profiles' => 'Support Agent,Administrator',
		    'menu_label' => 'Create ticket with last log...',
		    'menu_label/FR FR' => 'Créer une demande depuis le journal...',
		    'menu_tooltip' => 'Create a ticket based on last log entry...',
		    'menu_tooltip/FR FR' => 'Créer une demande basée sur la dernière entrée du journal...',
		    'icon' => 'far fa-comment-alt',
		    'form_label' => 'Create new request from %1$s',
		    'form_label/FR FR' => 'Nouvelle demande depuis %1$s',
		    'report_label' => 'Created from %1$s',
		    'report_label/FR FR' => 'Créée depuis %1$s',
		    'dest_class' => 'UserRequest',
		    'preset' => 
		    array (
		      0 => 'clone(caller_id,org_id,contacts_list,functionalcis_list)',
		      1 => 'copy(id,parent_request_id)',
		      2 => 'copy_head(public_log,description)',
		    ),
		    'retrofit' => 
		    array (
		    ),
		  ),
		  'MailInboxStandardToMailInboxOAuth' => 
		  array (
		    'source_scope' => 'SELECT MailInboxStandard WHERE finalclass = "MailInboxStandard"',
		    'allowed_profiles' => 'Administrator',
		    'menu_label' => 'Create OAuth 2.0 Mail Inbox...',
		    'menu_label/FR FR' => 'Créer une Boite mail OAuth 2.0...',
		    'form_label' => 'Create new OAuth 2.0 Mail Inbox from %1$s',
		    'form_label/FR FR' => 'Nouvelle Boite mail OAuth 2.0 depuis %1$s',
		    'report_label' => 'Created from %1$s',
		    'report_label/FR FR' => 'Créée depuis %1$s',
		    'dest_class' => 'MailInboxOAuth',
		    'preset' => 
		    array (
		      0 => 'clone(server, mailbox,login,port,behavior, target_class, ticket_default_values, ticket_default_title, title_pattern,unknown_caller_behavior,unknown_caller_rejection_reply,caller_default_values,error_behavior, notify_errors_to, notify_errors_from,trace,email_storage,target_folder,import_additional_contacts,stimuli )',
		      1 => 'set(active,no)',
		    ),
		    'retrofit' => 
		    array (
		    ),
		  ),
		),
	),
	'templates-base' => array (
		'view_extra_data' => 'relations',
	),
	'itop-stencils' => array (
		'rules' => array (
		  0 => 
		  array (
		    'name' => 'Child Request',
		    'trigger_class' => 'UserRequest',
		    'trigger_scope' => 'SELECT UserRequest',
		    'trigger_state' => 'New',
		    'report_label' => 'A ticket list has been created for the ticket',
		    'report_label/FR FR' => 'Une liste de tâche a été créée pour ce ticket',
		    'templates' => 'SELECT RequestTemplate  WHERE service_id = :trigger->service_id',
		    'copy_class' => 'UserRequest',
		    'copy_actions' => 
		    array (
		      0 => 'clone(name)',
		      1 => 'clone(description)',
		      2 => 'set(ticket_id,$trigger->id$)',
		      3 => 'set(team_id,$trigger->team_id$)',
		      4 => 'set(agent_id,$trigger->agent_id$)',
		    ),
		    'copy_hierarchy' => 
		    array (
		      'template_parent_attcode' => 'parent_id',
		      'copy_parent_attcode' => 'workorder_parent_id',
		    ),
		    'retrofit' => 
		    array (
		      0 => 'set(private_log,A task list has been created for the ticket)',
		    ),
		  ),
		),
	),
	'customer-survey' => array (
		'anonymous_survey' => false,
		'quiz_scale' => 'Pas concerné, Très insatisfait, Insatisfait, Satisfait, Très satisfait',
	),
);

/**
 *
 * Data model modules to be loaded. Names are specified as relative paths
 *
 */
$MyModules = array(
	'addons' => array('user rights' => 'addons/userrights/userrightsprofile.class.inc.php'),
);
?>